services:
  api:
    image: node:20
    command: >
      sh -c "npm run prisma:deploy && npm run prisma:generate && npm run dev"
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./services/api:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  worker:
    image: node:20
    command: npm run dev
    working_dir: /app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - ./services/worker:/app

  redis:
    image: redis